services:
  - type: web
    name: servify-backend
    env: node
    plan: free
    rootDir: backend
    region: frankfurt
    autoDeploy: true
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20
      - key: FRONTEND_URL
        value: https://servify-frontend.vercel.app
      - key: MONGODB_URI
        fromSecret: SERVIFY_MONGODB_URI
      - key: JWT_SECRET
        fromSecret: SERVIFY_JWT_SECRET
      - key: EMAIL_USER
        fromSecret: SERVIFY_EMAIL_USER
      - key: EMAIL_PASS
        fromSecret: SERVIFY_EMAIL_PASS
      - key: TWILIO_SID
        fromSecret: SERVIFY_TWILIO_SID
      - key: TWILIO_AUTH_TOKEN
        fromSecret: SERVIFY_TWILIO_AUTH_TOKEN
      - key: TWILIO_PHONE_NUMBER
        fromSecret: SERVIFY_TWILIO_PHONE
      - key: ABSTRACT_API_KEY
        fromSecret: SERVIFY_ABSTRACT_API

